### PR TITLE
Cast flags to i2s_mode_t in I2S config defaults (AUD-2588)

### PR DESCRIPTION
**Pull request by justintconroy**
Using these macros in C++ code doesn't build. Adding the explicit cast fixes the issue.

### CODE REVIEW

**Comment by jason-mao** [comment]
Thank you for your contribution

**Comment by justintconroy** [comment]
@jason-mao Any chance this will get merged some time soon?

**Comment by jason-mao** [comment]
@justintconroy I would like do it. Could you please help rebase the latest master?

**Comment by justintconroy** [comment]
@jason-mao done.

**Comment by justintconroy** [comment]
@jason-mao ping

**Comment by naveed-kinoo** [comment]
@jason-mao any updates, thanks.

**Comment by jason-mao** [comment]
Merged by 72753c70ce2be54a78ded671dff3942803805156

**Pull request closed without merging**
