### PR TITLE
Update board.h (AUD-2625)

### PR DESCRIPTION
**Pull request by c-logic**
No #include / no compile

### CODE REVIEW

**Comment by douardda** [comment]
This PR indeed fix the compilation bug, but it should have a better commit message: it should at least mention this fixes the  get-started/ play_mp3 example in the commit message subject (see https://chris.beams.io/posts/git-commit/ )

**Comment by jason-mao** [comment]
@douardda Would you please change the branch name to `bugfix/example_build_error` and make the commit message clearly. Thank you.

**Comment by jason-mao** [comment]
And how to reproduced this error?

**Comment by jason-mao** [comment]
Fixed on f67fb23b44aba35de2ddab0f7748114669c775b8

**Pull request closed without merging**
