### PR TITLE
Fix compilation warning that is treated as an error "-Wstringop-truncation" -O2 (AUD-2594)

### PR DESCRIPTION
**Pull request by raldone01**
I also removed an unnecessary strlen call. If there is a better way to remove the warning feel free to change my code.

### CODE REVIEW

**Comment by raldone01** [comment]
Mhh the CLA markdown seems broken.

**Comment by jason-mao** [comment]
@raldone01 Thank you for your contribution. Would you please change the branch name to `bugfix/xxxx`?

**Comment by jason-mao** [comment]
And how to reproduced this error?

**Comment by raldone01** [comment]
I am using:
Toolchain: `esp-2020r3-8.4.0`
ESP-IDF: `ESP-IDF v4.3-dev-2940-g6e776946d`
And the compiler flag `-Wall`.

**Pull request closed without merging**
