### PR TITLE
[esp_peripherals] Stop using deprecated functions in periph_console.c (AUD-3177)

### PR DESCRIPTION
**Pull request by sU8U7SfkcwTJVH7PjaVmej7D**
You get warnings with a recent esp-idf.

### CODE REVIEW

**Comment by sU8U7SfkcwTJVH7PjaVmej7D** [comment]
@jason-mao @HengYongChao : When can I expect this to be reviewed? Last merged PR is from February, which makes me wonder if there are still some Espressif people reading contributors PR's. Thanks!

**Comment by HengYongChao** [comment]
@jason-mao  PTAL.

**Comment by jason-mao** [comment]
@sU8U7SfkcwTJVH7PjaVmej7D Thank you for your contribution.

**Comment by jason-mao** [comment]
Merged by c7609dafdabf38a0f99026b205deed17575d5da8

**Pull request closed without merging**
