### PR TITLE
Update board_def.h (AUD-2123)

### PR DESCRIPTION
**Pull request by NU-LL**
Avoid compile errors

### CODE REVIEW

**Comment by jason-mao** [comment]
@NU-LL How to reproduced this error?

**Comment by NU-LL** [comment]
> @NU-LL How to reproduced this error?

The macro TOUCH_PAD_NUMx will be used later. The same problem has been solved in /components/audio_board/lyrat_v4_3, you can check [lyrat_v4_3/board_def.h](https://github.com/espressif/esp-adf/blob/master/components/audio_board/lyrat_v4_3/board_def.h) for details.

**Comment by meltdown03** [comment]
I think the Kaluga V1.2 has an issue also. I had to do this to get the buttons to work in the pipeline_raw_http example:
``` bash
diff --git a/components/audio_board/esp32_s2_kaluga_1_v1_2/board_def.h b/components/audio_board/esp32_s2_kaluga_1_v1_2/board_def.h
index 6f89b10..470d7b7 100644
--- a/components/audio_board/esp32_s2_kaluga_1_v1_2/board_def.h
+++ b/components/audio_board/esp32_s2_kaluga_1_v1_2/board_def.h
@@ -58,32 +58,32 @@ extern audio_hal_func_t AUDIO_CODEC_ES8311_DEFAULT_HANDLE;
 
 #define INPUT_KEY_DEFAULT_INFO() {                      \
      {                                                  \
-        .type = PERIPH_ID_BUTTON,                       \
+        .type = PERIPH_ID_ADC_BTN,                       \
         .user_id = INPUT_KEY_USER_ID_REC,               \
         .act_id = BUTTON_REC_ID,                        \
     },                                                  \
     {                                                   \
-        .type = PERIPH_ID_BUTTON,                       \
+        .type = PERIPH_ID_ADC_BTN,                       \
         .user_id = INPUT_KEY_USER_ID_MODE,              \
         .act_id = BUTTON_MODE_ID,                       \
     },                                                  \
     {                                                   \
-        .type = PERIPH_ID_TOUCH,                        \
+        .type = PERIPH_ID_ADC_BTN,                        \
         .user_id = INPUT_KEY_USER_ID_SET,               \
         .act_id = BUTTON_SET_ID,                        \
     },                                                  \
     {                                                   \
-        .type = PERIPH_ID_TOUCH,                        \
+        .type = PERIPH_ID_ADC_BTN,                        \
         .user_id = INPUT_KEY_USER_ID_PLAY,              \
         .act_id = BUTTON_PLAY_ID,                       \
     },                                                  \
     {                                                   \
-        .type = PERIPH_ID_TOUCH,                        \
+        .type = PERIPH_ID_ADC_BTN,                        \
         .user_id = INPUT_KEY_USER_ID_VOLUP,             \
         .act_id = BUTTON_VOLUP_ID,                      \
     },                                                  \
     {                                                   \
-        .type = PERIPH_ID_TOUCH,                        \
+        .type = PERIPH_ID_ADC_BTN,                        \
         .user_id = INPUT_KEY_USER_ID_VOLDOWN,           \
         .act_id = BUTTON_VOLDOWN_ID,                    \
     }                                                   \
```

**Comment by Yohannfra** [comment]
Hello @jason-mao , can this be merged ?

**Comment by jason-mao** [comment]
@NU-LL Thank you for your contribution.

**Pull request closed without merging**
